### ISSUE TITLE
errors to console

### ISSUE THREAD

**Issue by alexey2baranov** [MatAtBread/fast-async#10]
Hello!  Can this plugin output unhandled error to err stream?

```
async function someFunctionWithUncatchedError(){
    throw new Error(123);  //nothing output from hire to err stream/ silent break function and very hard to debug code
    try {
        throw new Error(123);   //this error will be handled
    }
    catch(er){
        console.error(er)    
    }
}

someFunctionWithUncatchedError();
```

**Comment by matAtWork** [comment]
In the example you have given, the first throw will be passed back to the caller - how are you invoking someFunctionWithUncatchedError()? If you're not catching the error (by invoking it without `await`, or not having a `try...catch` somewhere higher up in the stack, the error will be an uncaught rejection as handled by your Promise implementation (which you can log, ignore, etc).

There's a bit more of a discussion on how to do this correctly in https://github.com/MatAtBread/nodent/issues/44

**Comment by alexey2baranov** [comment]
ok i gotit. this would be helpfull for any others
http://www.2ality.com/2016/04/unhandled-rejections.html
