### ISSUE TITLE
Runtime included when not needed

### ISSUE THREAD

**Issue by SimonDegraeve** [MatAtBread/fast-async#16]
The runtime is inlined even when the file does not include any async call.

**Comment by matAtWork** [comment]
Just commit fast-async@6.1.0 to master which should address the issues you spotted (and another one from @rush about nodent and babel fighting over which one should map stack traces).

I'm not a big babel user, so if you want to pull this down and check it doesn't break anything you're doing, I'd appreciate any feedback before I npm publsh

**Comment by SimonDegraeve** [comment]
It looks good to me. Thank you.

**Comment by SimonDegraeve** [comment]
I notices few typo in the README
> v6.1.x can also refernce the runtme via

And

> The runtime need only be included once
