### ISSUE TITLE
6.1.1: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by gfortaine** [MatAtBread/fast-async#19]
I have a 'regeneratorRuntime is not defined' bug with 6.1.1 (everything was fine with previous versions)

My .babelrc is similar to the minimal .babelrc example :

`{
  "plugins": ["fast-async"]
}`

**Comment by matAtWork** [comment]
Can you provide a git repo or details for your setup? It sounds like Babel is not picking up your settings (from the .babelrc or package.json) as fast-async doesn't refer to regeneratorRuntime except in the tests, so Babel is trying it's "normal" async transforms and failing.

**Comment by gfortaine** [comment]
Hello,

Please find below the different settings for my setup:

[.babelrc](https://gist.github.com/gfortaine/fc38ab82a0d1acf82ec7e5cd9e7ce89el)

[package.json](https://gist.github.com/gfortaine/9e3ed21f1e8fdb76fe3fa577b506de66)

[webpack.dev.config.js](https://gist.github.com/gfortaine/010c57ca6e4d4b7d341e697d365f1203)

Everything was fine up to fast-async 6.0.34 (I am using it since 6.0.30)

**Comment by gfortaine** [comment]
If it could help, I am also putting the file where I am making my async / await call :

[Fetch.js](https://gist.github.com/gfortaine/379bbe9f2d71ba6ac68f3d3ff2530c32)

**Comment by matAtWork** [comment]
It's really not possible to work out what the setup is from that - there's almost certainly some unexpected interaction between the plugins. I've created a simple test that works fine.

```
git clone https://github.com/matAtWork/fast-async-minimal.git
cd fast-async-minimal
npm i
npm test
```

Looks good to me. I suggest cutting down your build to see if you can identify what interaction is causing problems. If I had to guess, I'd say fast-async needs to be early in your list of plugins, since I think something else in your tool-chain is transpiling async and await before fast-async has a chance to.

Did anything else change in your setup?

**Comment by gfortaine** [comment]
Hi,

Tried to use es2015 (instead of latest) in my .babelrc and put fast-async as first plugin in the array, without any success.

It clearly seems that there is a bug with the new version.

**Comment by MatAtBread** [comment]
There may be a bug, but I can't work out what it is without some help!

Can you start from the minimal set and add your options in until it fails?

**Comment by matAtWork** [comment]
I've just added the es2015 preset - still works

**Comment by gfortaine** [comment]
I don't manage to get the minimal set working right now (because of a Windows PC imposed by my company...). I will try it later today.

**Comment by gfortaine** [comment]
Got it. It was the [stage-0](https://babeljs.io/docs/plugins/preset-stage-0/) preset in my .babelrc. It loaded stage-3 presets that contained transform-async-to-generator...

Thank you for your support 👍

**Comment by matAtWork** [comment]
NP. I'm glad it wasn't a bug :)
