### ISSUE TITLE
Plugin breaks since babel-core 6.16

### ISSUE THREAD

**Issue by ephemer** [MatAtBread/fast-async#25]
It fails [here](https://github.com/MatAtBread/fast-async/blob/master/plugin.js#L98) because apparently `filename` has been renamed to `sourceFileName` in 6.16+.

I can make a pull request for this change if you like

**Comment by matAtWork** [comment]
That'd be nice. Can you make it check for both names so it still works with previous babel-builds?

**Comment by ephemer** [comment]
Good idea, will do
