### ISSUE TITLE
Does this work with babel-preset-es2017?

### ISSUE THREAD

**Issue by nikolay** [MatAtBread/fast-async#28]
https://github.com/babel/babel/tree/master/packages/babel-preset-es2017

**Comment by matAtWork** [comment]
It appears to (just tried from the cli) , although you probably want to remove the babel-plugin-transform-async-to-generator or make sure fast-async transforms before the default babel async transform.

**Comment by matAtWork** [comment]
...or alternatively don't use es2017 and just include babel-plugin-syntax-trailing-function-commas

**Comment by nikolay** [comment]
Or why don't you suggest Babel to use your `fast-async` instead of `babel-plugin-transform-async-to-generator`?

**Comment by MatAtBread** [comment]
Feel free to suggest it to them. I'm sure @sebmck is happy with the current Babel solution tho. Babel's plugin architecture is very capable, and you easily create your own presets and publish them if you wish.

I'll close this issue as there's no solution I can provide in fast-async or nodent

**Comment by nikolay** [comment]
@MatAtBread There's this module I will to use and will publish here the solution with it if it work: https://www.npmjs.com/package/modify-babel-preset

**Comment by matAtWork** [comment]
Good luck :)
