### ISSUE TITLE
try/finally not working?

### ISSUE THREAD

**Issue by djMax** [MatAtBread/fast-async#43]
I don't have detailed repro steps yet, but this seems to confuse fast-async:

```
try {
  // some stuff
  try {
    // some more stuff
  } finally {
    // cleanup stuff
  }
  // super important stuff
} catch (error) {
  // whatever
}
```

Basically, after "cleanup stuff" is run, it just falls off into the ether somewhere. "super important stuff" is never run.

**Comment by matAtWork** [comment]
If you can provide an example, I'll take a look - through http://nodent.mailed.me.uk/ is good. There are a few test cases in the nodent repo to catch just this kind of thing, but it's possible there's an edge case I haven't covered. The tests are in https://github.com/MatAtBread/nodent/tree/master/tests/semantics - mainly the files with 'try' in the filename.

**Comment by matAtWork** [comment]
I'm going to close this as I don't have an example I can reproduce. Feel free to re-open if you can provide a basic test case
