### ISSUE TITLE
[Bug] 6.3.2 - Error: Cannot find module '@babel/helper-module-imports'

### ISSUE THREAD

**Issue by le0nik** [MatAtBread/fast-async#53]
`@babel/helper-module-imports` is being used in `plugin.js` but is not present in `package.json`'s dependencies.

```
Error: Cannot find module '@babel/helper-module-imports'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at module.exports (*****/fast-async/plugin.js:10:25)
```

**Comment by SeeThruHead** [comment]
also seeing this
fast-async/plugin.js still requires that file.

**Comment by rjharmon** [comment]
this can also affect users of neutrino's 'web' and 'react' presets.

**Comment by jzaefferer** [comment]
Looks like the dependency was removed here: https://github.com/MatAtBread/fast-async/commit/ad8383f38ed1ff6c939f2bdbcca48565dccbdd5d - its unclear though why it was removed without any other changes.

For now `6.3.1` is still working fine.

**Comment by eliperelman** [comment]
@rjharmon I have shipped Neutrino v8.2.2 to pin this version of fast-async mentioned by @jzaefferer.

**Comment by trusktr** [comment]
I came to open the same error, but then I saw this issue.

I depend on fast-async `^6.3.0`, and the new `6.3.2` is breaking my project with

```
    Cannot find module '@babel/helper-module-imports'
```

**Comment by matAtWork** [comment]
Apologies - I managed to mess up separating babel-7 beta dependancies from v6. 

v6.3.4 published with no v7-beta dependencies.
v7.01.1 published for use with babel-7-beta.

Please re-open if this update does not fix the issue in your configuration.
