### ISSUE TITLE
Cannot await non-Promises.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [MatAtBread/fast-async#59]
Using Babel 6, it appears right now that I cannot `await` any non-Promise value. E.g. 

```js
(async () => { await 1 })()
```

throws `Uncaught (in promise) TypeError: 1.then is not a function`. Is this by design, or is there something wrong with my setup?

**Comment by AndreasCag** [comment]
With babel 7 your snippet works fine 🤔

**Comment by AndrewSouthpaw** [comment]
Sorry, to clarify I'm using Babel 6...

**Comment by matAtWork** [comment]
This is documented in https://github.com/MatAtBread/nodent#differences-from-the-es7-specification

Nodent (used by fast-async) by default doesn't allow waiting on a non-promise as it's a significant performance hit. You can change the default to permit this using the fast-async `spec` or `wrapAwait ` compiler options (see https://github.com/MatAtBread/fast-async#usage).

fast-async@7 sets this by default (you can unset it if you wish), by popular demand.
