### ISSUE TITLE
generators:false not honored - still outputs code using generators

### ISSUE THREAD

**Issue by rjgotten** [MatAtBread/fast-async#67]
Even when specifying `generators:false` a source function

```js
(async () => {
  await Promise.all([a, b]);
  console.log("ready");
});
```

generates

```js
(function* () {
  yield Promise.all([a, b]);
  console.log("ready");
})();
```

which continues to use generators.

Using fast-async 7.0.6

**Comment by verydanny** [comment]
This is because you have to disable the generator options in `@babel/preset-env`. Like so:

```js
module.exports = {
  presets: [
    ['@babel/env', {
      modules: false,
      targets: {
        browsers: ['last 2 Chrome versions'],
      },
      exclude: [
        'transform-async-to-generator',
        'transform-regenerator',
      ],
    }],
  ],
  plugins: [
    ['module:fast-async', {
      spec: true,
    }],
  ],
}
```

**Comment by rjgotten** [comment]
Yup. I just noticed this myself as well.
The config I was working off of, was only disabling regenerator, and not the actual async-to-generator transformation. Doh! (Of all the stupid oversights...)

Closing this, as it's invalid.
