### ISSUE TITLE
Clobbers single line function definition export

### ISSUE THREAD

**Issue by naturalethic** [MatAtBread/fast-async#7]
Will rewrite an exported function into a non-exported given for example:

`export async function foo() {}`

This then requires a manual export later in the file.

**Comment by simonbuchan** [comment]
I get this even for non-`async` functions:

```
% cat export.js
export function test() {
  return 1;
}
% babel --presets es2015 --plugins fast-async export.js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

Function.prototype.$asyncbind = <snip>;

function test() {
  return 1;
}
```

And `export default function` will error with "ReferenceError: $1 is not defined":
```
% babel --presets es2015 --plugins fast-async export_default.js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

Function.prototype.$asyncbind = <snip>

exports.default = $1;
function test() {
  return 1;
}
```

**Comment by MatAtBread** [comment]
Thanks for pointing this one out. Can you tell me the exact versions of fast-async, nodent and acorn-es7-plugin that was installed in your test environment, as I fixed some export-async issues recently. I'm unable to when through issues for a week as I'm away, but will get these patches when I'm back

**Comment by naturalethic** [comment]
For myself:
```
fast-async@6.0.31
nodent@2.6.2
acorn-es7-plugin@1.0.17
```

**Comment by MatAtBread** [comment]
They're all latest, so it might be something I've missed. However, this might be a Babel issue, as the online compiler (same versions as you - no Babel, just nodent and acorn doing the transpiling) seems to generate good code:

http://nodent.mailed.me.uk/#export%20async%20function%20foo()%20%7B%7D

**Comment by MatAtBread** [comment]
@simonbuchan's comment would seem to support the theory it's a Babel issue, but I'll take a look anyway, unless you determine this one way or the other in advance

**Comment by simonbuchan** [comment]
Well they export fine without `--plugins fast-async`, or with the regenerator based transform plugins, but it does look like an interaction with Babel's module transform

**Comment by nightwolfz** [comment]
Having the same issues

**Comment by MatAtBread** [comment]
Out of interest, what happens if you reverse the order of the plugins (ie fast-async before the presets). I'm still away so I can't test this myself for a few days!

**Comment by MatAtBread** [comment]
Fixed in fast-async@6.0.32

**Comment by naturalethic** [comment]
Confirmed.  Thanks!

**Comment by MatAtBread** [comment]
NP :)
